# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history_trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=-1)),
                ('amount', models.IntegerField(default=-1)),
                ('timestamp', models.IntegerField(default=-1)),
                ('token_id', models.IntegerField(default=-1)),
                ('volumn', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('type', models.IntegerField(default=-1)),
                ('price', models.IntegerField(default=-1)),
                ('amount', models.IntegerField(default=-1)),
                ('timestamp', models.IntegerField(default=0)),
                ('token_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=-1)),
                ('amount', models.IntegerField(default=-1)),
                ('timestamp', models.IntegerField(default=-1)),
                ('token_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
