# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='history_trade',
            new_name='HistoryTrade',
        ),
        migrations.AddField(
            model_name='trade',
            name='buyer',
            field=models.CharField(default='random', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='seller',
            field=models.CharField(default='random', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
